language: cpp
sudo: required
services: docker
env:
  global:
    - IMAGE_NAME=vasyahuyasa/remod

before_install:
  - sudo apt-get update
  - sudo apt-get install -y automake build-essential zlib1g-dev
 
compiler:
  - gcc

script:
  - cd src && make && make clean

docker_build:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - cd ..
  - docker build --pull --cache-from "${IMAGE_NAME}:latest" -t "${IMAGE_NAME}:latest" -t "${IMAGE_NAME}:${TRAVIS_TAG}" .

docker_push_to_registry:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true
